trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSource: "spec"
      versionSpec: "18.x"
      checkLatest: true
    displayName: "Install Node.js"

  # Install dependencies in the root folder
  - task: Npm@1
    displayName: "Installing Modules in Root"
    inputs:
      command: "install"
      workingDir: "."

  # Install dependencies in the client folder
  - task: Npm@1
    displayName: "Installing Modules in /client"
    inputs:
      command: "install"
      workingDir: "client"

  # Install dependencies in the server folder
  - task: Npm@1
    displayName: "Installing Modules in /server"
    inputs:
      command: "install"
      workingDir: "server"

  # Build the client application
  - task: Npm@1
    displayName: "Building Modules in /client"
    inputs:
      command: "custom"
      workingDir: "client"
      customCommand: "run build"

  - task: CopyFiles@2
    inputs:
      Contents: |
        client/build/**
        server/**
      TargetFolder: "$(Build.ArtifactStagingDirectory)"

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: "$(Build.ArtifactStagingDirectory)"
      ArtifactName: "release"
      publishLocation: "Container"

  - script: npm start
    displayName: "Start MERN Application"
