name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
      - stage/*
      - release/*

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:4.4
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install frontend dependencies
        run: |
          cd client
          npm install

      - name: Build frontend
        run: |
          cd client
          npm run build

      - name: Install backend dependencies
        run: |
          cd server
          npm install

      - name: Archive build artifacts
        run: |
          tar -czf client-build.tar.gz -C client/build .
          tar -czf server-build.tar.gz -C server .

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: client-build
          path: client-build.tar.gz

      - name: Upload server artifacts
        uses: actions/upload-artifact@v2
        with:
          name: server-build
          path: server-build.tar.gz

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download client build artifact
        uses: actions/download-artifact@v2
        with:
          name: client-build
          path: ./client-build

      - name: Download server build artifact
        uses: actions/download-artifact@v2
        with:
          name: server-build
          path: ./server-build

      - name: Deploy frontend to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "AuthInMern" # Replace with your Azure Web App name for frontend
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: "./client-build/client-build.tar.gz" # Adjust path if necessary

      - name: Deploy backend to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "AuthInMern" # Replace with your Azure Web App name for backend
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: "./server-build/server-build.tar.gz" # Adjust path if necessary
